services:
  db:
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
    ports:
      - '5432:5432'  # External access (for connecting from the host)
    volumes:
      - group-project:/var/lib/postgresql/data
      - ./init_data:/docker-entrypoint-initdb.d
  web:
    image: node:lts
    user: 'node'
    working_dir: /repository
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - '10000:10000'
    volumes:
      - ./:/repository
    # change the command to `npm run testandrun` to run mocha. 'npm start' does not run the tests
    command: 'npm start'
    #command: 'npm run testandrun'
volumes:
  group-project:
